import { useEffect, useState } from "react";
import api from "../api/axios";

const generateSKU = () => {
  const timestamp = Date.now().toString(36).toUpperCase();
  const random = Math.random().toString(36).substring(2, 5).toUpperCase();
  return `SKU-${timestamp}-${random}`;
};

export default function ProductModal({ open, onClose, product, onSubmit }) {
  const [formData, setFormData] = useState({
    name: "",
    sku: "",
    price: "",
    quantity: "",
    minStock: "",
    supplierId: "",
  });
  const [suppliers, setSuppliers] = useState([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const fetchSuppliers = async () => {
      try {
        const response = await api.get("/suppliers");
        setSuppliers(response.data);
      } catch (err) {
        console.error(err);
      }
    };
    fetchSuppliers();
  }, []);

  useEffect(() => {
    if (open) {
      if (product) {
        setFormData({
          name: product.name,
          sku: product.sku,
          price: product.price,
          quantity: product.quantity,
          minStock: product.minStock,
          supplierId: product.supplierId?._id || product.supplierId,
        });
      } else {
        setFormData({
          name: "",
          sku: generateSKU(),
          price: "",
          quantity: "",
          minStock: "",
          supplierId: "",
        });
      }
      setError("");
    }
  }, [open, product]);

  const handleChange = (event) => {
    const { name, value } = event.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    setLoading(true);
    setError("");

    try {
      // Convert numeric fields to numbers
      const dataToSubmit = {
        ...formData,
        price: parseFloat(formData.price),
        quantity: parseInt(formData.quantity, 10),
        minStock: parseInt(formData.minStock, 10),
      };
      console.log("Submitting product data:", dataToSubmit);
      await onSubmit(dataToSubmit);
      onClose();
    } catch (err) {
      console.error("Error response:", err.response?.data);
      setError(err.response?.data?.message || "Failed to save product");
    } finally {
      setLoading(false);
    }
  };

  if (!open) return null;

  const title = product ? "Edit Product" : "Add Product";

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-panel" onClick={(event) => event.stopPropagation()}>
        <div className="modal-header">
          <h3>{title}</h3>
          <button type="button" className="modal-close" onClick={onClose}>
            ×
          </button>
        </div>
        <form className="modal-form" onSubmit={handleSubmit}>
          <label>
            Product Name
            <input
              type="text"
              name="name"
              value={formData.name}
              onChange={handleChange}
              required
            />
          </label>
          <label>
            SKU
            <input
              type="text"
              name="sku"
              value={formData.sku}
              onChange={handleChange}
              disabled={!product}
              readOnly={!!product}
              required
            />
            {!product && <small style={{color: '#6b7280', marginTop: '4px', display: 'block'}}>Auto-generated by system</small>}
          </label>
          <label>
            Price (₹)
            <input
              type="number"
              name="price"
              value={formData.price}
              onChange={handleChange}
              min="0"
              step="0.01"
              required
            />
          </label>
          <label>
            Quantity
            <input
              type="number"
              name="quantity"
              value={formData.quantity}
              onChange={handleChange}
              min="0"
              required
            />
          </label>
          <label>
            Min Stock
            <input
              type="number"
              name="minStock"
              value={formData.minStock}
              onChange={handleChange}
              min="0"
              required
            />
          </label>
          <label>
            Supplier
            <select
              name="supplierId"
              value={formData.supplierId}
              onChange={handleChange}
              required
            >
              <option value="">Select a supplier</option>
              {suppliers.map((supplier) => (
                <option key={supplier._id} value={supplier._id}>
                  {supplier.name}
                </option>
              ))}
            </select>
          </label>
          {error ? <p className="form-error">{error}</p> : null}
          <div className="modal-actions">
            <button type="button" className="button button-secondary" onClick={onClose}>
              Cancel
            </button>
            <button type="submit" className="button button-primary" disabled={loading}>
              {loading ? "Saving..." : "Save Product"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
